# Generated by Django 6.0 on 2025-12-20 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mediajob',
            constraint=models.UniqueConstraint(fields=('file_hash', 'preset'), name='unique_file_hash_preset'),
        ),
    ]
