# Generated by Django 6.0 on 2025-12-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediajob',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many times the job was executed'),
        ),
    ]
