# Generated by Django 6.0 on 2025-12-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapp', '0002_mediajob_unique_file_hash_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediajob',
            name='callback_url',
            field=models.URLField(blank=True, help_text='Webhook URL to notify on completion', null=True),
        ),
    ]
